version: '3'

services:  

  cig:
    image: andrewjouffray/composite_image_generator:latest
    restart: "no"
    environment:
      - input_path=raw_input_data/weeds1-new/

      - dataset_name="weeds"

      - output_path=input_data/

      - background_path=backgrounds/

      - max_objects_per_canvas=5

      - canvases_per_frame=5

      - save_bnd_box=true

      - save_masks_json=true

      - save_masks_png=false

      - canvas_lower_resolution=10

      - canvas_blurr=10

      - canvas_change_brightness=30

      - object_saturation=20

      - object_affine_transform=50
    volumes:
    - /run/media/andrew/research/workdir_weeds1:/workdir
    command: bash -c "cd /code/ && pwd && ls -l && ./start.sh"

